---
- name: deploiement de l'application 
  hosts: servers
  become: yes
  tasks:
          - name: deploiement de conteneur docker
            docker_container:
                    image: sihamlogwire/app:{{tag}}
                    name: sprint_project
                    state: started
                    auto_remove: true
                    ports:
                        - "8089:2222"
